### ISSUE TITLE
 Column E, rows 45-55 have not been included in the database

### ISSUE THREAD

**Issue by Nodragem** [Nodragem/InSciOut-Project#1]
Forwarded from @Radams86 :

I noticed that Column E, rows 45-55 have not been included in the database, which we need. Possible names and info below:

|Cell| Column name              |   content     |
| -- | ------------------------ | ------------- |
|E45 |	RCT_Synonym_Accept      |	code 0-2    |
|E46 |	RCT_Synonym_AcceptWTM   |	integer     |
|E47 |	RCT_Title_Accept        |	code 0-2    |
|E48 |	RCT_Title_AcceptWTM     |	integer     |
|E49 |	RCT_MS1_Accept          |	code 0-2    |
|E50 |	RCT_MS1_AcceptWTM       |	integer     |
|E51 |	RCT_MS2_Accept          |	code 0-2    |
|E52 |	RCT_MS2_AcceptWTM       |	integer     |
|E53 |	RCT_SDS_Accept          |	code 0-2    |
|E54 |	RCT_SDS_AcceptQuote     |	code 0-2    |
|E55 |	RCT_SDS_AcceptWTM       |	integer     |

**Comment by Nodragem** [comment]
I don't seem to have the problem on my side:
![screenshot-19052017](https://cloud.githubusercontent.com/assets/10520249/26249546/f1894792-3c9e-11e7-8628-8e8dbd366a7f.png)

I get these cells, and their column names are:

Section | Explanation | Column name
------- | ------- | -------
PR Manipulations | Experimental condition | RCT_Condition
x  | Synonym change | RCT_Synonym
x  | words to mention | RCT_Synonym_WordsTM
x  | Causal phrasing change title | RCT_Title
x  | words to mention | RCT_Title_WordsTM
x  | Causal phrasing change main statements 1. | RCT_MS1
x  | words to mention | RCT_MS1_WordsTM
x  | Causal phrasing change main statements 2. | RCT_MS2
x  | words to mention | RCT_MS2_WordsTM
x  | Design statement inserted (text) | RCT_SDS
x  | included in a quote? | RCT_SDS_Quote
x  | words to mention | RCT_SDS_WordsTM

As stated in `Column Names.csv`

**Comment by Radams86** [comment]
refer to issue on difference between the press release draft and final versions
