### ISSUE TITLE
The database does not contains Draft Press Release

### ISSUE THREAD

**Issue by Nodragem** [Nodragem/InSciOut-Project#5]
Note that the table `PR_table` seems to contains only the **Final Press Releases** at the moment.

Do you need the **Draft Press Releases**? I don't remember why I removed it.

If you want us to keep the Draft Press Release, we will need to make views as we did with `JABody_table` and `JATitle_table`. In other words, we would have `PRDraft_table` and `PRFinal_table` views.

**Comment by Radams86** [comment]
Yes we need these both the draft and the final press release for the trial data. 
There is some example trial data on the Google drive: /Insciout Project/The TRIAL/Information for Geoffrey/InSciOut Project/rawdata/sample trial data

Note however that the information in rows 44-55 is slightly different, hence we need the 2 sets of variable names that I sent before.

**Comment by Nodragem** [comment]
Now PR_table contains the Draft Press Release.
Be careful though (@Radams86  @aimschallenger  @lbratton ) some of your SQL code may need to be updated to take into account this change in the table PR_table.

**Comment by Nodragem** [comment]
I reopen the issue as the problem was not solved.
